const ActionTypes = {
  // alerts actions
  PUSH_ALERT: 'PUSH_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  CLEAR_ALL_ALERTS: 'CLAER_ALL_ALERTS',
  CLEAR_ALL_ERRORS: 'CLEAR_ALL_ERRORS',
  CLEAR_ALL_WARNINGS: 'CLEAR_ALL_WARNINGS',
  CLEAR_ALL_INFOS: 'CLEAR_ALL_INFOS',

  //user actions
  LOG_IN_USER: 'LOG_IN_USER'
}

export default ActionTypes;